plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: 'https://raw.githubusercontent.com/toss/yarn-workspace-plugin-since/main/bundles/%40yarnpkg/plugin-workspace-since.js'

yarnPath: .yarn/releases/yarn-berry.cjs
