plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-workspace-plugin-since/main/bundles/%40yarnpkg/plugin-workspace-since.js"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
