name: configure
description: Configure to Toss Payments workflows
runs:
  using: 'composite'
  steps:
    - name: GitHub Profile 설정
      run: |
        git config user.name "tosspayments-bot"
        git config user.email "70372587+tosspayments-bot@users.noreply.github.com"
      shell: bash
